version: '3.3'
services:
  test_app:
    image: bmort/health_check_test:latest
    ports:
      - 5000:5000
    healthcheck:
      test: curl -f -s http://localhost:5000/ || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    build:
      context: .
      dockerfile: Dockerfile
