version: "3.3"

services:

  dn:
    image: alpine:3.6
    deploy:
      mode: global
      labels:
        com.dn.description: "Default networking"
    command: sleep 3600

  hn:
    image: alpine:3.6
    deploy:
      mode: global
      labels:
        com.dn.description: "Host networking"
    networks:
      - my_host
    dns_search: .
    command: sleep 3600

networks:
  my_host:
    driver: bridge