version: "3.3"

services:

  flask_server:
    image: bmort/flask_hello
    build:
      context: ./flask_hello
    deploy:
      mode: global

  udp_socket_server:
    image: bmort/udp_socket_server
    build:
      context: ./udp_socket_server
    deploy:
      mode: global
