version: "3.3"

services:

  flask_hello_default:
    image: bmort/flask_hello
    ports:
      - 5602:5502
    deploy:
      mode: global
      labels:
        com.dn.description: "Default networking"

  flask_hello_host:
    image: bmort/flask_hello
    networks:
      - outside
    deploy:
      mode: global
      labels:
        com.dn.description: "Host networking"

networks:
  outside:
    external:
      name: "host"
