version: '3.3'
services:
  file_writer:
    image: bmort/file_writer:latest
    command: file_writer.py
    volumes:
      - type: bind
        source: ./output
        target: /app/output
    build:
      context: .
      dockerfile: Dockerfile
