version: "3.3"
services:
  file_writer:
    image: bmort/file_writer:latest
    volumes:
      - type: bind
        source: .
        target: /app
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M
      restart_policy:
        condition: none
