version: '3.3'

services:

  kibana:

    image: bmort/kibana-logtrail
    ports:
      - '80:5601'
    #volumes:
    #  - ./kibana-logtrail/logtrail.json:/usr/share/kibana/plugins/logtrail/logtrail.json
    networks:
      - elk
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager

networks:
  elk:
    external:
      name: elk_default
