version: '3.3'

services:
  log_spammer:
    image: bmort/logging_spammer:latest
    network:
      - elk_default
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s
